### ISSUE TITLE
이미지 로드하는 소스가 제거되어 이미지가 본문에서 보이지 않는 경우가 생깁니다.

### ISSUE THREAD

**Issue by wookho** [mAKEkr/XE-addon-multimedia_thumbnail#10]
https://www.xetown.com/qna/766469

게시글 수정 단계에서도 해당 소스가 지워져 있어 db에서 지워진 줄 알았으나 실제 db에는 이미지경로 소스가 남아있어 어떤 자료의 문제인지 확인하다가 찾았습니다.

**Comment by mAKEkr** [comment]
해당문제는 이미지로 alt를 첨부하는 애드온/모듈과 충돌하여 발생하는 문제로 보입니다. 2.0.0에선 rel="" 로 썼는데 HTMLPurifier에서 rel attribute에 대하여 승인하지않아 섬네일이 제대로 반영되지않던 문제가 있어서 2.1.0에 alt attribute로 변경하는 패치를 진행했습니다.
이미지 태그 삭제시에 alt값 조회를 강화하는 방식으로 패치를 진행하겠습니다.
