### ISSUE TITLE
2.5 베타 버전에서 첫 저장 시에 섬네일 본문에 나타나는 현상

### ISSUE THREAD

**Issue by saymehan** [mAKEkr/XE-addon-multimedia_thumbnail#13]
새로 공개하신 2.5 베타 버전 테스트 중입니다.

섬네일 생성 관련해서는 특별한 이상은 없으나
글 작성 후 본문에 섬네일이 제일 상단에 나타납니다.

하지만 글을 다시 열어 저장하면 섬네일 사라져 괜찮기는 한데
다시 한번 저장해야 하는 불편이 있네요.

http://www.airtravelinfo.kr/xe/air_news/1259929 (지금은 정상입니다.)

xe 1.9.2
php 7.1

감사합니다.

**Comment by mAKEkr** [comment]
작동원리상 게시물 수정시에 섬네일이 제일 상단에 나오는것은 있어선 안됩니다.
![default](https://user-images.githubusercontent.com/2796198/36652121-ef755fd8-1aef-11e8-9a01-c176aa62888c.PNG)
이런식으로 원래 본문에 첨부되어 필터링되지않는 멀티미디어 썸네일을 가리고 있는 상황인데요, 혹시 게시물에 섬네일이 남는다면 섬네일이 남는 게시물을 하나 테스트로 만들어주실 수 있으실지 궁금합니다.

**Comment by mAKEkr** [comment]
해당 이슈에 대해서 조사 불가/피드백 불가로 인하여 문제가 아닌것으로 판단, 이슈 종결합니다.
