### ISSUE TITLE
확장변수 멀티미디어 체크

### ISSUE THREAD

**Issue by d2d2** [mAKEkr/XE-addon-multimedia_thumbnail#18]
확장변수 멀티미디어 체크하는 기능은 구현 계획이 없으신지요?;;

**Comment by mAKEkr** [comment]
해당부분은 이전에 2.1 이전에 구현되어있었습니다만 다음과 같은 이유로 해당 코드가 삭제되었습니다

- XE측에서 확장변수에 태그가 들어가는것을 보안취약점으로 보고있습니다. 이로인해 지속적으로 코어단에서 패치되는것을 우회할수 없어서 결정내렸습니다.
- 태그를 사용하지않고 URL만 입력하는 방식의 oEmbed를 지원할 계획이 없습니다.
- 해당 기능에 문제가 있었지만 몇달넘게 피드백이 없어서 해당 기능을 이용하는 이용자가 없음으로 판단했습니다.

아직도 이러한 제 생각은 관철되지 않았습니다.
확장변수를 이용하여 embed코드를 사용하는 애드온/스킨/모듈등이 있다면 사례를 알려주시면 검토 후 다시 살릴것인지 판단해보겠습니다.
