### ISSUE TITLE
일반회원의경우 img주석태그가 필터로인해 사라집니다.

### ISSUE THREAD

**Issue by bjrambo** [mAKEkr/XE-addon-multimedia_thumbnail#2]
실제일반회원의 경우 어떠한특정스타일때문에 태그자체가 필터링되어 주석img가 삭제됩니다.

**Comment by mAKEkr** [comment]
관리자만 작동하는건가요? HTMLPurifier의 옵션을 체크해봐야될듯 하네요

**Comment by bjrambo** [comment]
@mAKEkr display:none 옵션에 의해 img태그가 사라지는것같습니다.
차라리 클래스를 하나 생성하도록하고, 해당 클래스를 css파일 로딩 같이 해서 display:none옵션을 넣어버리는게 제일깔끔했습니다.

http://rhyboum.com/video <- 실사용중

**Comment by mAKEkr** [comment]
@bjrambo 감사합니다 한번 테스트환경 구축 후 확인해보도록 할게요

**Comment by inguide** [comment]
일반회원이 글올리면 섬네일 생성이 역시 안되고 있습니다.

**Comment by airbogo** [comment]
저도 일반회원 안되서 왔는데 버전업 하실때 꼭 적용해주시기 바랍니다.

**Comment by mAKEkr** [comment]
@inguide @airbogo 이미 현재 인지하고있는 상황으로 핫픽스버전을 내놓은 뒤에 기능추가를 하는쪽으로 선회하려 계획중입니다.

**Comment by mAKEkr** [comment]
@bjrambo 확인해본결과 XE최신버전에서 style태그를 지우거나 해도 해당 증상이 해결되지 않는걸로 보아서 style에 의한 필터링 문제는 아닌듯 보입니다. 이슈는 일단 정리를 위해 종결해두겠습니다.
