### ISSUE TITLE
video 태그에서도 썸네일을 가져올 수 있으면 좋겠습니다

### ISSUE THREAD

**Issue by cydemo** [mAKEkr/XE-addon-multimedia_thumbnail#3]
video 태그를 사용해서 멀티미디어를 삽입하는 경우가 더러 있으니, 이 부분도 애드온에서 처리가 되면 좋을 거 같아서요.
(혹시 버전업 작업이 마무리 단계라든가 그런 아니시겠죠;;;)

오늘 이런 이야기가 있기도 했구요.
https://www.xetown.com/square/600085#comment_600212
까먹고 있다가 이슈 남겨봅니다.

**Comment by mAKEkr** [comment]
video태그의 poster항목을 긁어오는건 차후 3.0.0뒤에 안정화를 거치면 제작하도록 하겠습니다. 제작 진행과정은 해당 이슈에 서술하는것으로 대체하겠습니다. 의견 감사합니다 :)

**Comment by cydemo** [comment]
감사합니다~! 즐거운 마음으로 기다리겠습니다 ^^/
