### ISSUE TITLE
NAVER TV 영상 썸네일 생성도 되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by ghost** [mAKEkr/XE-addon-multimedia_thumbnail#4]
http://serviceapi.rmcnmv.naver.com/flash/outKeyPlayer.nhn?vid=블라블라

주소가 이런 식으로 되어 있는 영상의 썸네일은 생성되지 않는 것 같아요.

그리고 vlive.tv , kakaotv.daum.net 영상은 나오지가 않아서 썸네일이 생성되는지도 

확인하지 못했는데 만일 썸네일이 생성되지 않는다면 이것도 썸네일이 생성되게 했으면 좋겠습니다.

**Comment by mAKEkr** [comment]
감사합니다, 한번 리버싱 후 체크해서 썸네일을 가져올 수 있는 방법이 존재하는지 체크해본 뒤에 해당 이슈를 통해 알려드리겠습니다. 감사합니다 :)

**Comment by inguide** [comment]
https:// 로 넣어야 영상이 나옵니다. 썸네일 생성은 안되고요.. 이점 수정 부탁드립니다.

**Comment by mAKEkr** [comment]
@inguide 해당 이슈와는 부적합한 내용인것같습니다. 따로 새로운 이슈를 작성해주신 뒤에 오류증상과 재현방식, 그리고 #6 이슈에 적어둔 주소에서 재발하는지 체크 부탁드립니다.

**Comment by mAKEkr** [comment]
해당 embed서비스를 네이버에서 중단한듯 보여 해당 이슈를 종료합니다
