### ISSUE TITLE
스케쥴 및 릴리즈 진행과정

### ISSUE THREAD

**Issue by mAKEkr** [mAKEkr/XE-addon-multimedia_thumbnail#5]
- [x] XE최신버전 섬네일 규칙 체크 -> 2017년 8월 31일까지(사이트 작업진행과 함께 병행)
- [x] XE코어용 호환성 확보
- [x] 확장변수내의 멀티미디어 섬네일 체크할것인지 결정(기존기능 삭제)
- [x] 버그패치된 2.1.0 배포
- [x] 3.0.0 개발 시작
- [x] 라이믹스(XE Fork CMS)용 호환성 확보
- [ ] 테스트 3.0.0pre 배포
- [ ] 이상없을경우 3.0.0-stable 배포
- [ ] 네이버TV, 티비플등의 외부서비스 추가 및 API점검(사운드클라우드 서비스 여부)
- [ ] 서비스 추가 및 기능추가인 3.1.0버전 배포
- [x] 라이센스 변경
- [ ] 1주일간 테스트 및 버그 리포트를 받은 뒤 이상없을경우 프로젝트 개발중단

**Comment by cydemo** [comment]
완전 멋있으십니다! 기대돼요. 2017년 9월 두근두근 ♡

**Comment by mAKEkr** [comment]
개발이 주업이 아니게되어서 작업이 조금 더딜지 모릅니다. 많이 기다리게 해드려서 염치없지만, 양해좀 구하겠습니다.

**Comment by mAKEkr** [comment]
2.1.0 릴리즈 완료하였습니다.
- Github Release 게시완료
- XpressEngine 자료실 게시완료

**Comment by mAKEkr** [comment]
2.5.0-beta 릴리즈 완료하였습니다.
- Github Release 게시완료

XpressEngine 자료실에는 정식버전이 배포될때 게시하도록 하겠습니다.

**Comment by mAKEkr** [comment]
2.5.1 릴리즈 완료하였습니다.
XpressEngine 자료실에는 게시하지 않습니다.
