### ISSUE TITLE
3.0.0 성능 최적화 및 코드개선

### ISSUE THREAD

**Issue by mAKEkr** [mAKEkr/XE-addon-multimedia_thumbnail#9]
- [ ] addon.php에서의 중복과정 간소화 
  - 수정시에 MultimediaThumb의 섬네일을 삭제하면서 MultimediaThumb의 섬네일을 체크하는 이중으로 되고있음
     - API종류의 Request에선 작동할지 모르겠음. 이에 대해서 코드를 일단 개선한 뒤에 오류접수가 생길경우 버그수정을 할 계획
  - 사용하지 않는 변수 삭제 및 변수명 개선
- [ ] Class 네이밍 및 스트럭쳐 개선
  - checkDocumentThumbExists와 같은이름
    - check와 exists가 의미하는바가 비슷하므로 중복선언이나 다름없음
  - checkMultimediaThumb는 삭제하는쪽으로 진행
  - 외부리퀘스트(json,xml)에 대해서 따로 메소드를 분리
  - 구버전 XE에 대한 지원중단(checkXEVersion 메소드 삭제) 
- [ ] services.php 생성
  - 정규식 형테에 따라서 서비스명과 몇개의 변수가 필요한지 담아내는 형태. 이를 모아서 서비스를 적용하는 방식으로 추진
  - 서비스를 추가하더라도 애드온의 업데이트 없이 사용자가 코드 한줄을 추가하는 형태로 개선
  - 멀티미디어 포맷생성/멀티미디어포맷형태/섬네일 주소를 관리하도록 담당

기타 추가사항이 있으면 해당이슈 내용을 수정하는것이 아닌 덧붙이는 형태로 이어감

**Comment by mAKEkr** [comment]
- [ ] Class와 addon.php에서 $o~~ 형태의 변수(ex:$oFileModel)을 $xe~~ 형태(ex: $xeFileModel)로 변경
- [ ] services.php로 변경시 addon.php및 info.xml에서 설정을 대응을 못할수있음을 감안하여 설계할것

**Comment by airbogo** [comment]
혹시 3.0에 반영이 되는지 모르겠지만 문의글 하나 남깁니다.
유투브 공유주소 입력시 섬네일도 생성되게 해주세요 ^^
소스붙여넣기로는 섬네일 생성이 잘되는데요 유튜브 공유주소로 붙어 넣으면 안됩니다.

**Comment by mAKEkr** [comment]
@airbogo 해당부분은 멀티미디어 섬네일 애드온쪽에서 의도하는것이 아니기때문에 반영하지않습니다. 다른 애드온을 개발/요청하시는쪽을 고려해보시는것을 권장합니다.

**Comment by haendel8** [comment]
저도 airbogo님께서 말씀하신 부분이 좀 아쉽네요.
embed코드를 수동으로 입력하기 보다는 주소만 적고 oEmbed로 글쓰는 경우가 대부분이라..^^;
